apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-promstack-kube-prometheus-alertmanager
  namespace: utils
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: promstack
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: "smtp.example.com:587"    # <--- change
      smtp_from: "alerts@example.com"           # <--- change
      smtp_auth_username: "alerts@example.com"  # <--- change
      smtp_auth_password: "REPLACE_ME"          # <--- change or use a k8s secretRef
      smtp_require_tls: true

    route:
      receiver: team-email
      group_by: [service]
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 2h
      routes:
        - matchers:
            - severity="critical"
          receiver: team-email

    receivers:
      - name: team-email
        email_configs:
          - to: "your-inbox@example.com"       # <--- change
            send_resolved: true
