apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-services
  namespace: utils
  labels:
    release: promstack  # must match your Prometheus serviceMonitorSelector
spec:
  namespaceSelector:
    matchNames: ["app"]  # scrape Services in the "app" namespace
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend-traffic
          - api-errors
          - api-latency
  endpoints:
    - port: http          # MUST match the Service port name
      path: /metrics
      interval: 5s
      scheme: http

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promstack-kube-state-metrics
  namespace: utils
  labels:
    release: promstack
spec:
  namespaceSelector:
    matchNames: ["utils"]
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: promstack
  endpoints:
    - port: http
      path: /metrics
      interval: 30s