grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
    path: /
    pathType: Prefix

prometheus:
  enabled: true

prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.localhost
      paths:
        - /
      pathType: Prefix
    service:
      type: ClusterIP
