apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-observability-k8s
  namespace: utils
spec:
  project: default
  source:
    repoURL: https://github.com/s1natex/Monitoring-observability-k8s
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
